# Generated by Django 4.2 on 2023-05-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disablings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=60, verbose_name='Статус')),
                ('resource', models.CharField(max_length=60, verbose_name='Отключаемый ресурс')),
                ('reason', models.CharField(max_length=60, verbose_name='Причина отключения')),
                ('disable_dt', models.DateTimeField(verbose_name='Дата отключения')),
                ('enable_dt', models.DateTimeField(verbose_name='Дата включения')),
                ('fact_dt', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата включения')),
            ],
            options={
                'verbose_name': 'Отключение',
                'verbose_name_plural': 'Отключения',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120, verbose_name='Тип документа')),
                ('title', models.CharField(max_length=200, verbose_name='Тайтл')),
                ('file', models.FileField(upload_to='documents', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
