# Generated by Django 4.2 on 2023-05-28 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='home.home', verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='disablings',
            name='aparment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disablings', to='home.apartment', verbose_name='Квартира'),
        ),
    ]
