# Generated by Django 4.1.5 on 2023-02-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='times',
            new_name='timed',
        ),
    ]
