# Generated by Django 4.1.5 on 2023-02-12 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_apartment_level_alter_homelevel_home'),
        ('events', '0002_rename_times_events_timed'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='home',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.home'),
        ),
    ]
