# Generated by Django 4.1.5 on 2023-02-23 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_staff_home'),
        ('events', '0003_events_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='home',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='home.home'),
        ),
    ]
