# Generated by Django 4.1.5 on 2023-02-23 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_apartment_options_alter_home_options_and_more'),
        ('events', '0004_alter_events_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Ивент', 'verbose_name_plural': 'Ивенты'},
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='events',
            name='end',
            field=models.DateTimeField(verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='events',
            name='home',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='home.home', verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='events',
            name='start',
            field=models.DateTimeField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='events',
            name='timed',
            field=models.BooleanField(blank=True, verbose_name='Завершено'),
        ),
    ]
