# Generated by Django 4.2 on 2023-06-02 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesstokens',
            options={},
        ),
        migrations.AlterModelOptions(
            name='refreshtokens',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_confirmed_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_password_change',
        ),
        migrations.AlterField(
            model_name='accesstokens',
            name='token',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accesstokens',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accesstokens',
            name='valid_to',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='refreshtokens',
            name='access',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.accesstokens'),
        ),
        migrations.AlterField(
            model_name='refreshtokens',
            name='token',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='refreshtokens',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refreshtokens',
            name='valid_to',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterModelTable(
            name='accesstokens',
            table=None,
        ),
        migrations.AlterModelTable(
            name='refreshtokens',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
