# Generated by Django 4.1.5 on 2023-02-24 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesstokens',
            options={'verbose_name': 'Токен доступа', 'verbose_name_plural': 'Токены доступа'},
        ),
        migrations.AlterModelOptions(
            name='refreshtokens',
            options={'verbose_name': 'Токен обновления', 'verbose_name_plural': 'Токены обновления'},
        ),
        migrations.AlterField(
            model_name='accesstokens',
            name='token',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='accesstokens',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Для пользователя'),
        ),
        migrations.AlterField(
            model_name='accesstokens',
            name='valid_to',
            field=models.DateTimeField(default=None, verbose_name='Действителен до'),
        ),
        migrations.AlterField(
            model_name='refreshtokens',
            name='access',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.accesstokens', verbose_name='Токен доступа'),
        ),
        migrations.AlterField(
            model_name='refreshtokens',
            name='token',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='refreshtokens',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Для пользователя'),
        ),
        migrations.AlterField(
            model_name='refreshtokens',
            name='valid_to',
            field=models.DateTimeField(default=None, verbose_name='Действителен до'),
        ),
    ]
