# Generated by Django 4.2 on 2023-05-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Тайтл')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('description', models.TextField(verbose_name='Текст новости')),
                ('image', models.ImageField(upload_to='news', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
