# Generated by Django 4.2 on 2023-05-28 20:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number', models.IntegerField(default=0, verbose_name='Номер квартиры')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=128, verbose_name='Улица')),
                ('home_number', models.CharField(max_length=16, verbose_name='Номер дома')),
                ('microdistrict', models.CharField(max_length=126, verbose_name='Микрорайон')),
                ('area', models.FloatField(verbose_name='Площадь')),
                ('create_dt', models.DateTimeField(verbose_name='Дата основания')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалён из системы')),
                ('jitsi', models.CharField(blank=True, default=uuid.UUID('105a4020-646b-41a2-b0a7-06a250d61ce1'), max_length=128, unique=True, verbose_name='GUID конференции')),
                ('messanger_link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на мессенджер')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=70, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=70, verbose_name='Отчество')),
                ('role', models.CharField(max_length=50, verbose_name='Должность')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='home.home', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
            },
        ),
        migrations.CreateModel(
            name='HomeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, verbose_name='Этаж')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='home.home', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Этаж',
                'verbose_name_plural': 'Этажи',
            },
        ),
    ]
