# Generated by Django 4.1.4 on 2023-01-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelevel',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
