# Generated by Django 4.2 on 2023-05-28 20:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='jitsi',
            field=models.CharField(blank=True, default=uuid.UUID('7b081912-3ec1-4a63-adb9-a5d9df77af96'), max_length=128, unique=True, verbose_name='GUID конференции'),
        ),
    ]
