# Generated by Django 4.1.4 on 2023-01-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homelevel_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='apartment_number',
            field=models.IntegerField(default=0),
        ),
    ]
