# Generated by Django 4.1.5 on 2023-02-12 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_apartment_apartment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='home.homelevel'),
        ),
        migrations.AlterField(
            model_name='homelevel',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='home.home'),
        ),
    ]
