# Generated by Django 4.1.5 on 2023-02-23 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='home.home'),
        ),
    ]
