# Generated by Django 4.1.5 on 2023-02-23 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_alter_staff_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='users',
            field=models.ManyToManyField(related_name='homes', to=settings.AUTH_USER_MODEL),
        ),
    ]
