# Generated by Django 4.1.5 on 2023-02-23 22:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_home_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='jitsi',
            field=models.CharField(default=uuid.UUID('f55de5ef-a42b-47f8-9a80-a5d265884612'), max_length=128),
        ),
    ]
