# Generated by Django 4.1.5 on 2023-02-23 22:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_home_jitsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='jitsi',
            field=models.CharField(default=uuid.UUID('26e7e3a3-e2dc-4d95-9940-08998538610c'), max_length=128, unique=True),
        ),
    ]
