# Generated by Django 4.1.5 on 2023-02-23 22:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_home_jitsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='jitsi',
            field=models.CharField(default=uuid.UUID('4d5f87be-70c7-497b-808c-e9a2cca35bc6'), max_length=128),
        ),
    ]
