# Generated by Django 4.1.5 on 2023-02-23 23:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_home_jitsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='jitsi',
            field=models.CharField(default=uuid.UUID('0f1dc269-1c32-410d-b995-afc67640e643'), max_length=128),
        ),
    ]
