# Generated by Django 4.1.5 on 2023-02-23 23:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_home_jitsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='jitsi',
            field=models.CharField(blank=True, default=uuid.UUID('d18fc602-2ac5-4e49-a02c-89263cda2c41'), max_length=128, unique=True),
        ),
    ]
