# Generated by Django 4.1.5 on 2023-02-23 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_alter_home_jitsi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
        migrations.AlterModelOptions(
            name='homelevel',
            options={'verbose_name': 'Этаж', 'verbose_name_plural': 'Этажи'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Персонал', 'verbose_name_plural': 'Персонал'},
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apartment_number',
            field=models.IntegerField(default=0, verbose_name='Номер квартиры'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='home.homelevel', verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Жилец'),
        ),
        migrations.AlterField(
            model_name='home',
            name='area',
            field=models.FloatField(verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='home',
            name='create_dt',
            field=models.DateTimeField(verbose_name='Дата основания'),
        ),
        migrations.AlterField(
            model_name='home',
            name='home_number',
            field=models.CharField(max_length=16, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='home',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалён из системы'),
        ),
        migrations.AlterField(
            model_name='home',
            name='jitsi',
            field=models.CharField(blank=True, default=uuid.UUID('a7a75d4d-f759-4a68-8812-3b8336bd747e'), max_length=128, unique=True, verbose_name='GUID конференции'),
        ),
        migrations.AlterField(
            model_name='home',
            name='microdistrict',
            field=models.CharField(max_length=126, verbose_name='Микрорайон'),
        ),
        migrations.AlterField(
            model_name='home',
            name='street',
            field=models.CharField(max_length=128, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='home',
            name='users',
            field=models.ManyToManyField(related_name='homes', to=settings.AUTH_USER_MODEL, verbose_name='Жильцы'),
        ),
        migrations.AlterField(
            model_name='homelevel',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='home.home', verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='homelevel',
            name='level',
            field=models.IntegerField(default=0, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(max_length=70, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='home.home', verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(max_length=70, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='middle_name',
            field=models.CharField(max_length=70, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(max_length=50, verbose_name='Должность'),
        ),
    ]
