# Generated by Django 4.1.5 on 2023-02-24 10:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_apartment_options_alter_home_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='jitsi',
            field=models.CharField(blank=True, default=uuid.UUID('595ee7cb-cce9-4bbb-958e-6bb3792c71d1'), max_length=128, unique=True, verbose_name='GUID конференции'),
        ),
    ]
