# Generated by Django 4.2 on 2023-05-28 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=64, verbose_name='Статус')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('theme', models.CharField(max_length=256, verbose_name='Тема')),
                ('text', models.TextField(verbose_name='Текст')),
                ('done_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='home.home', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
    ]
