# Generated by Django 4.1.5 on 2023-02-23 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_staff_home'),
        ('reqs_to_company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='home.home'),
        ),
    ]
