# Generated by Django 4.1.5 on 2023-02-23 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0014_alter_apartment_options_alter_home_options_and_more'),
        ('reqs_to_company', '0002_alter_requests_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requests',
            options={'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.AlterField(
            model_name='requests',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='done_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='home.home', verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.CharField(blank=True, max_length=64, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='theme',
            field=models.CharField(max_length=256, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='От кого'),
        ),
    ]
