# Generated by Django 4.1.5 on 2023-02-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('theme', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Тема')),
                ('author_email', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['id'],
            },
        ),
    ]
