# Generated by Django 4.1.5 on 2023-02-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author_email',
            field=models.CharField(max_length=64, verbose_name='Почта задавшего вопрос'),
        ),
    ]
