# Generated by Django 4.1.5 on 2023-02-23 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0014_alter_apartment_options_alter_home_options_and_more'),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votes',
            options={'verbose_name': 'Голосование', 'verbose_name_plural': 'Голосования'},
        ),
        migrations.AlterModelOptions(
            name='votesvariants',
            options={'verbose_name': 'Вариант голосования', 'verbose_name_plural': 'Варианты голосования'},
        ),
        migrations.AlterField(
            model_name='votes',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.home', verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='isActive',
            field=models.BooleanField(blank=True, default=False, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='theme',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='votesvariants',
            name='for_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='votes.votes', verbose_name='Относится к голосованию'),
        ),
        migrations.AlterField(
            model_name='votesvariants',
            name='label',
            field=models.CharField(max_length=128, verbose_name='Текст варианта'),
        ),
        migrations.AlterField(
            model_name='votesvariants',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Выбравшие этот вариант'),
        ),
    ]
